return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.18.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 16,
  tilewidth = 40,
  tileheight = 40,
  nextobjectid = 704,
  properties = {},
  tilesets = {
    {
      name = "Proto",
      firstgid = 1,
      tilewidth = 40,
      tileheight = 40,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "proto/actionMapHelper.png",
          width = 40,
          height = 40
        },
        {
          id = 1,
          image = "proto/camera.png",
          width = 40,
          height = 40
        },
        {
          id = 2,
          image = "proto/damageBlockGreen.png",
          width = 40,
          height = 40
        },
        {
          id = 3,
          image = "proto/damageBlockRed.png",
          width = 40,
          height = 40
        },
        {
          id = 4,
          image = "proto/damageBlockYellow.png",
          width = 40,
          height = 40
        },
        {
          id = 5,
          image = "proto/gamelogic.png",
          width = 40,
          height = 40
        },
        {
          id = 6,
          image = "proto/blockA.png",
          width = 40,
          height = 40
        },
        {
          id = 7,
          image = "proto/blockB.png",
          width = 40,
          height = 40
        },
        {
          id = 8,
          image = "proto/blockC.png",
          width = 40,
          height = 40
        },
        {
          id = 9,
          image = "proto/blockD.png",
          width = 40,
          height = 40
        },
        {
          id = 10,
          image = "proto/blockE.png",
          width = 40,
          height = 40
        },
        {
          id = 11,
          image = "proto/blockF.png",
          width = 40,
          height = 40
        },
        {
          id = 12,
          image = "proto/blockG.png",
          width = 40,
          height = 40
        },
        {
          id = 13,
          image = "proto/blockH.png",
          width = 40,
          height = 40
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "ignore",
      visible = false,
      opacity = 0.08,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 519,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 480,
          height = 640,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 640,
          width = 480,
          height = 640,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 539,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "content",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 362,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 679,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 680,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 681,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 684,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 685,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 686,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 687,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "foreground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 432,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 600,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 484,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 486,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 487,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 489,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 504,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 508,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 509,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 600,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 40,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 531,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 554,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 560,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 563,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 565,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 569,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 560,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 570,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 572,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 573,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 574,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 575,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 576,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 577,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 581,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 582,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 584,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 585,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 586,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 587,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 588,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 589,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 608,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 609,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 610,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 611,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 613,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 614,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 615,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 617,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 618,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 619,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 620,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 621,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 623,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 643,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 646,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 648,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 649,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 650,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 651,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 653,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 655,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 657,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 660,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 661,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 662,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 663,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 664,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 665,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 666,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 667,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 668,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 669,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 670,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 671,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 673,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 674,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 675,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 689,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 690,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 691,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 692,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 693,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 694,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 695,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 696,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 698,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 699,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 702,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
